Importing the Dependencies

In [29]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [30]:
# Loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv(r'C:\Users\Vikram\OneDrive\Desktop\ML Projects\Projects\10.1. Credit Card dataset.csv')

In [31]:
# First 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [32]:
# Dataset information 
credit_card_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [33]:
# Checking the number missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [34]:
# Distribution of Legit transaction & Fraudulent transaction
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This Dataset is highly unbalanced

0 --> Normal Transaction

1 --> Fraudulent Transaction

In [35]:
# Separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [36]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [37]:
# Statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [38]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [39]:
# Compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Under-Sampling

Build a sample dataset containing similar distribution of Normal transactions & Fraudulent transactions

Number of Fraudulent Transactions --> 492

In [40]:
legit_sample = legit.sample(n=492)

Concatenating 2 DataFrames

In [41]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [42]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
177650,123273.0,-0.146696,1.031631,0.149505,0.896339,0.979256,-0.085111,0.920344,-0.524437,-0.276037,...,-0.307835,-0.305626,0.163654,0.701675,-1.099403,0.426603,-0.235259,-0.188166,0.99,0
53695,46105.0,-1.830712,0.145016,0.257102,-0.499798,1.013021,4.349571,-1.209662,2.057850,0.286259,...,0.338941,0.632019,-0.228359,1.038418,0.051963,-0.365685,-0.113270,-0.104278,110.93,0
242392,151475.0,2.015917,-0.393382,-0.422194,0.336041,-0.434402,-0.050599,-0.657901,0.000571,1.138275,...,0.150973,0.668086,0.166407,0.656737,-0.205835,0.542334,-0.018429,-0.040154,8.04,0
209657,137653.0,-0.921625,1.429007,-2.350084,-1.590245,2.496158,3.163588,-0.129185,1.477105,0.033610,...,0.339404,1.168839,-0.001105,0.729144,-0.632199,-0.213406,0.324784,0.088435,0.89,0
32677,36914.0,0.994248,-0.441216,0.812742,1.462043,-0.873950,0.179584,-0.495803,0.286212,1.240324,...,-0.004172,0.055163,-0.112883,0.048002,0.494385,-0.246055,0.046101,0.030330,75.32,0

In [43]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [44]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,98124.447154,0.001432,0.024400,-0.068725,-0.018346,0.020088,-0.095941,-0.020360,-0.001997,-0.056450,...,-0.050114,0.033890,-0.007300,0.027807,-0.000076,-0.004852,-0.010941,0.013324,0.006611,80.390610
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Splitting the data into Features & Targets

In [45]:
X = new_dataset.drop(columns='Class')
Y = new_dataset['Class']

In [46]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
177650  123273.0 -0.146696  1.031631  0.149505  0.896339  0.979256 -0.085111
53695    46105.0 -1.830712  0.145016  0.257102 -0.499798  1.013021  4.349571
242392  151475.0  2.015917 -0.393382 -0.422194  0.336041 -0.434402 -0.050599
209657  137653.0 -0.921625  1.429007 -2.350084 -1.590245  2.496158  3.163588
32677    36914.0  0.994248 -0.441216  0.812742  1.462043 -0.873950  0.179584
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
177650  0.920344 -0.524437 -0.276037  ...  0.410875 -0.307835 -0.305626
53695  -1.209662  2.057850  0.286259  ... -0.186229  0.338941  0.632019
242392 -0.657901  0.000571  1.138275  ... -0.104113  0.150973  0.668086
209657 -0.129185  1.477105  0.033610  ...  0.156907  0.339404  1.168839
32677  -0.495803  0.286212  1.240324  ... -0.211620 -0.004172  0.055163
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
177650  0.163654  0.701675 -1.099403  0.426603 -0.235259 -0.188166    0.99
53695  -0.228359  1.038418  0.051963 -0.365685 -0.113270 -0.104278  110.93
242392  0.166407  0.656737 -0.205835  0.542334 -0.018429 -0.040154    8.04
209657 -0.001105  0.729144 -0.632199 -0.213406  0.324784  0.088435    0.89
32677  -0.112883  0.048002  0.494385 -0.246055  0.046101  0.030330   75.32
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [47]:
print(Y)

177650    0
53695     0
242392    0
209657    0
32677     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

Split the data into Training and Testing data

In [48]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [49]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

Model Training

Logistic Regression

In [50]:
model = LogisticRegression()

In [51]:
# Training the Logistic Regression model with Training data
model.fit(X_train, Y_train)

c:\Users\Vikram\OneDrive\Desktop\ML Projects\Projects\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy Score

In [52]:
# Accuracy on Training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [53]:
print(f"Accuracy on Training data: {training_data_accuracy}")

Accuracy on Training data: 0.9364675984752223

In [54]:
# Accuracy on Testing data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [55]:
print(f"Accuracy on Testing data: {test_data_accuracy}")

Accuracy on Testing data: 0.949238578680203